name:                llm-video-editor-types
version:             0.1.0.0
github:              "yarkivaev/llm-video-editor-types"
license:             BSD-3-Clause
author:              "Yaroslav"
maintainer:          "yarkivaev@gmail.com"
copyright:           "2025 Yaroslav"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Shared types for llm-video-editor and llm-video-editor-bot

dependencies:
- base >= 4.7 && < 5
- text
- time
- aeson
- aeson-pretty
- bytestring
- http-types
- http-client
- http-client-tls
- mtl
- directory
- process
- filepath

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Types
    - Types.Common
    - Types.Media
    - Types.Video
    - Types.Assembly
    - Types.System
    - Types.Render
    - Types.Transcoder
    - Types.LLMApi
    - Types.LLM
    - Action.Assemble
    - FFmpeg.Config
    - FFmpeg.Render
    - FFmpeg.Transcoder

tests:
  llm-video-editor-types-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - llm-video-editor-types
    - hspec
    - QuickCheck
    - mtl

  llm-video-editor-types-integration-test:
    main:                Spec.hs
    source-dirs:         integration-test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - llm-video-editor-types
    - hspec
    - QuickCheck
    - mtl
    - case-insensitive
    - temporary
    - process
    - time
    - text