resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/23/25.yaml

packages:
- .

extra-deps:
- git: https://github.com/yarkivaev/abstract-files.git
  commit: 1804c3e6e3e2900b70d2c4414ad54eb4058abd83